first_item = None


async def test_items_once(items):
    global first_item

    first_item = items[0]

    # 1000 items should have been inserted in database
    assert len(items) == 1000


async def test_items_twice(items):
    # we should still have 1000 items, not 2000 (the collection should
    # have been cleaned first)
    assert len(items) == 1000

    # this is the pregenerated id, it shouldn't change across tests
    assert items[0].fixed_id == first_item.fixed_id

    # a new _id is generated by MongoDB at every insert for every
    # item, so items shouldn't have the same _id across tests
    assert items[0]._id != first_item._id
